main:
	mvn exec:java -Dexec.mainClass="edu.cmu.demo.Main"

forceland:
	mvn exec:java -Dexec.mainClass="edu.cmu.demo.ForceLanding"

runmission:
	mvn exec:java -Dexec.mainClass="edu.cmu.demo.RunMission"

